import streamlit as st
from application_pages.page1 import run_page1
from application_pages.page2 import run_page2

st.set_page_config(layout="wide")

st.sidebar.title("Navigation")
selection = st.sidebar.radio("Go to", ["Data Generation & Preprocessing", "Model Training"])

if selection == "Data Generation & Preprocessing":
    run_page1()
elif selection == "Model Training":
    run_page2()

# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')